name: Update Network Timezones

on:
  push:
  pull_request:

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: github.actor == 'miigotu'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.0a1
      - name: Lint
        run: |
          pip install poethepoet
          cd sb_network_timezones
          poetry install --no-root
          poe poetry_update
          poe lint